export type { LocaleDefinition } from '@faker-js/faker';
export { defaultConfig } from './config.js';
export { configFromOptions, createGenerator, fixture } from './fixture.js';
export type {
  AnyNode,
  ArrayNode,
  BigIntConstraints,
  BigIntNode,
  BooleanNode,
  CatchNode,
  CustomNode,
  DateConstraints,
  DateNode,
  DefaultNode,
  Derivation,
  EnumNode,
  FixtureGenerator,
  FixtureOptions,
  GenContext,
  Generator,
  GeneratorConfig,
  IntersectionNode,
  LazyNode,
  LiteralNode,
  ManyOptions,
  MapNode,
  NaNNode,
  NeverNode,
  NodeType,
  NodeTypeMap,
  NullableNode,
  NullNode,
  NumberConstraints,
  NumberNode,
  ObjectNode,
  OptionalNode,
  Override,
  OverrideMatcher,
  PipeNode,
  PromiseNode,
  ReadonlyNode,
  RecordNode,
  SchemaAdapter,
  SchemaNode,
  SetNode,
  SizeConstraints,
  StringConstraints,
  StringNode,
  SymbolNode,
  TemplateLiteralNode,
  TupleNode,
  UndefinedNode,
  UnionNode,
  UnknownNode,
  VoidNode,
} from './schema.js';
export {
  emptyBigIntConstraints,
  emptyDateConstraints,
  emptyNumberConstraints,
  emptySizeConstraints,
  emptyStringConstraints,
} from './schema.js';
