import type { GenContext } from '@l4n3/fakeish';
import { fixture } from '@l4n3/fakeish';
import { z } from 'zod';

// .generator() replaces the default generator for a specific node type.
// The custom generator receives a GenContext with the node, path, faker, etc.

const userSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.email(),
  bio: z.string(),
  score: z.number().min(0).max(100),
});

// Replace the string generator — every string field uses the custom logic

const withCustomStrings = fixture(userSchema, { seed: 42 }).generator('string', (ctx: GenContext) => {
  const fieldName = ctx.path.at(-1) ?? 'unknown';
  return `custom-${fieldName}-${ctx.sequence}`;
});

const user = withCustomStrings.one();
console.log('Custom string generator:', user);
// name, bio, and email are all generated by the custom generator

// Replace the number generator — produce sequential values

const withSequentialNumbers = fixture(userSchema, { seed: 42 }).generator(
  'number',
  (ctx: GenContext) => (ctx.sequence + 1) * 10,
);

const users = withSequentialNumbers.many(3);
console.log('\nSequential numbers:');
for (const u of users) {
  console.log(`  id=${u.id}, score=${u.score}`);
}

// Chain multiple generator replacements

const fullyCustom = fixture(userSchema, { seed: 42 })
  .generator('string', (ctx: GenContext) => `${ctx.path.at(-1)}-value`)
  .generator('number', () => 42);

const customUser = fullyCustom.one();
console.log('\nFully custom generators:', customUser);
